### ISSUE TITLE
Requirments

### ISSUE THREAD

**Issue by rjmonteiro** [jrodriguez-rc/abap-dev-utilities#4]
Hello,

I was trying to install in abapGIT but i get a popup about the requirements and if I countinue it gives me error

<img width="709" alt="Screenshot_1" src="https://user-images.githubusercontent.com/5887399/142660614-aa677bec-4e7d-41ed-a19b-5c84363eb261.png">
31
<img width="551" alt="Screenshot_2" src="https://user-images.githubusercontent.com/5887399/142660626-9890ee8f-c50c-4ff2-ab2d-68160ad367d5.png">
<img width="218" alt="Screenshot_3" src="https://user-images.githubusercontent.com/5887399/142660627-680fab18-73a2-4ede-9fc4-49aa9f31ec81.png">
<img width="520" alt="Screenshot_4" src="https://user-images.githubusercontent.com/5887399/142660630-b6e0922c-90ab-47cb-bac5-be98b3837a05.png">

**Comment by jrodriguez-rc** [comment]
Hi @rjmonteiro, sorry for the delay.

There was a path version error checking the requirements, which I fixed for this repository in commit 391fc35fcf17df3978229d40b055a7dfedab0aba

**Comment by jrodriguez-rc** [comment]
Fix requested for abapGit https://github.com/abapGit/abapGit/pull/5223
